### ISSUE TITLE
Request for DTE historical outage data

### ISSUE THREAD

**Issue by keenanmat** [mtfurlan/dte-outage-history#1]
Hi mtfurlan, myself and a team of researchers at the university of michigan are looking to create a query system to poll the DTE outage information (as you did here). Could you please send over some historical data on outage information you have polled from this site? Really any information and historical data you have would be of assistance. We are looking to potentially add in a few more layers into a broader project that represents outage duration and occurrence in DTE's service area.

For the historical data, I'm sure it takes up quite a bit of space, so for now just a sample of historical data you have acquired would be helpful if possible.

Lastly, any extra documentation you have to navigate through the code would be extremely helpful.

Also, great work on the application and thanks for making this an open source project.

Thank you!
-Matt

**Comment by mtfurlan** [comment]
Hey Matt,
There is a sample of what the data I have looks like here: https://raw.githubusercontent.com/mtfurlan/dte-outage-history/main/db/raw.geojson
I'm happy to share all of my data, I just don't have a good way to transfer all of it.
After I started gzipping it it got *much* smaller, but it's still tens of GB. (I think, I'm not at home right now to check)
Could mail you a flash drive, or meet up somewhere.

Are you interested in working together on tooling to reassemble this into a queryable format?

**Comment by keenanmat** [comment]
Hi mtfurlan, I see now. Thanks for sending that link over. We are going to review the source code a bit and also the formatting of the data and discuss. If we do decide to pursue this option further, I will get back to you and we can discuss this more. Thanks again!

**Comment by mtfurlan** [comment]
The only real code I've done is the scraping of the geojson from arcgis.
Everything else is a like an afternoon of playing about at best.

I *think* I got the rest of it to the point where I could import a single export into a database, and then render it on a map, but I didn't get to trying to combine events across multiple exports.

**Comment by keenanmat** [comment]
I'm going to be taking a look throughout the week. The scrape/poll of the entire region is really the only thing we are interested in. Then, the rendering into a specific format is something we'll discuss later on too.

**Comment by mtfurlan** [comment]
It's 80GB of data right now, and the readme has the dates I cover.

**Comment by keenanmat** [comment]
Understood, thanks mtfurlan. I'll get back to you on where we go with this.

**Comment by keenanmat** [comment]
Hi mtfurlan, I talked to the team, and we would really like to have the historical data as well if you would still be willing to provide it. If there is a way we could either transfer the data over the internet (which I know would be difficult given 80 GB), or, we could try to meet in person/send through mail a flash drive or SD or something similar (in which we would reimburse you for any data storage device as needed). Please let me know if this is something we could setup and what your prefer method would be to send the data. We would really appreciate it! Thank you very much, -Matt

**Comment by mtfurlan** [comment]
Data transferred via sneakernet.
