### ISSUE TITLE
Request for DTE outage data

### ISSUE THREAD

**Issue by Davidxswang** [mtfurlan/dte-outage-history#2]
Hi mtfurlan, thanks for this great project!
I am a PhD student at Wayne State University and doing research on power system resilience. My research team is very interested in the data you collected for the past few years. We would really appreciate your help if you could send us the data you've already collected. We can send you an empty USB flash drive and reimburse you for the mailing fee if you think it is okay.

Thanks again for your help!

**Comment by mtfurlan** [comment]
Replied to email.
